[package]
name = "papo"
version = "0.1.0"
authors = ["Andriel Ferreira <andrielfr@proton.me>"]
edition = "2024"
publish = false
license = "Apache-2.0"
repository = "https://github.com/AmanoTeam/Papo"
description = "GTK client for WhatsApp Web"

[profile.release]
lto = true

[dependencies]
# UI
adw = { version = "0.8", package = "libadwaita", features = ["v1_8"] }
relm4 = { version = "0.10", features = ["libadwaita", "gnome_48"] }
relm4-components = { version = "0.10", features = ["libadwaita"] }
tracker = "0.2"

# Utilities
strum = { version = "0.27", features = ["derive"] }
os_info = "3.14"
# humantime = "2.3"
country-emoji = "0.3"
rlibphonenumber = "0.3"

# Logging
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# Localization
gettext-rs = { version = "0.7", features = ["gettext-system"] }

# WhatsApp
image = { version = "0.25", default-features = false, features = [
  "png",
  "jpeg",
  "webp",
] }
glycin = { version = "3.0", features = ["gdk4"] }
qrcode = { version = "0.14", default-features = false, features = ["image"] }

# Futures
tokio = { version = "1.49", features = ["rt", "rt-multi-thread", "sync"] }
futures-util = { version = "0.3", default-features = false, features = [
  "std",
  "async-await",
] }

[dependencies.wacore]
git = "https://github.com/jlucaso1/whatsapp-rust"
rev = "28d8e00c980e506a52c6d387559df5284e1cb17c"

[dependencies.waproto]
git = "https://github.com/jlucaso1/whatsapp-rust"
rev = "28d8e00c980e506a52c6d387559df5284e1cb17c"

[dependencies.whatsapp-rust]
git = "https://github.com/jlucaso1/whatsapp-rust"
rev = "28d8e00c980e506a52c6d387559df5284e1cb17c"

[dependencies.whatsapp-rust-tokio-transport]
git = "https://github.com/jlucaso1/whatsapp-rust"
rev = "28d8e00c980e506a52c6d387559df5284e1cb17c"

[dependencies.whatsapp-rust-ureq-http-client]
git = "https://github.com/jlucaso1/whatsapp-rust"
rev = "28d8e00c980e506a52c6d387559df5284e1cb17c"
