[package]
name = "papo"
version = "0.1.0"
authors = ["Andriel Ferreira <andrielfr@proton.me>"]
edition = "2024"
publish = false

[profile.release]
lto = true

[dependencies]
adw = { version = "0.8.1", package = "libadwaita", features = ["v1_8"] }
relm4 = { version = "0.10.1", features = ["libadwaita", "gnome_48"] }
relm4-components = { version = "0.10.1", features = ["libadwaita"] }

# Logging
tracing = "0.1.44"
tracing-subscriber = "0.3.22"

# Localization
gettext-rs = { version = "0.7.7", features = ["gettext-system"] }
